### ISSUE TITLE
Axes don't affect the mining speed of blocks that they're normally supposed to

### ISSUE THREAD

**Issue by DoubleJester** [Silversmith-Mods/Verdant#1]
Like the title says, axes don't affect the mining speed of blocks like logs, planks and crafting tables when Verdant is installed.

The only mods used were:
Fabric API 0.92.2+1.20.1
Moonlight Lib 1.20-2.13.41-fabric
Verdant 1.20.1-0.1.0-fabric

Really sorry if I reported the bug wrong.

**Comment by AstralOrdana** [comment]
fixed for 0.1.1
